#!/bin/sh
set -e
# ====================================
# Install packages
# ====================================

# dig is part of bind-tools
# hostname is part of inetutils
sudo pacman -S --noconfirm --needed \
                alacritty \
                base-devel \
                bc \
                bind-tools \
                chromium \
                curl \
                dunst \
                feh \
                firefox-developer-edition \
                fzf \
                go \
                htop \
                i3-gaps \
                inetutils \
                jq \
                k9s \
                kubectl \
                kubectx \
                libnotify \
                libreoffice \
                maim \
                man-db \
                neovim \
                net-tools \
                nm-connection-editor \
                noto-fonts-cjk \
                ntfs-3g \
                openssh \
                pulseaudio-alsa \
                pulsemixer \
                pyenv \
                python-pip \
                python-poetry \
                python3 \
                ripgrep \
                rofi \
                slock \
                thunar \
                tmux \
                udisks2 \
                unclutter \
                unzip \
                wget \
                xclip \
                xdotool \
                xorg-server \
                xorg-xinit \
                xorg-xrandr \
                xorg-xset \
                yarn \
                zathura \
                zathura-pdf-mupdf \
                zip \
                zsh \
                zsh-syntax-highlighting

if pacman -Qs yay > /dev/null ; then
    echo "Yay is already installed, moving on..."
else
    pushd /tmp
    rm -rf yay
    git clone https://aur.archlinux.org/yay.git
    pushd yay
    makepkg -si --noconfirm
    popd
    rm -rf yay
    popd
fi

# TODO: Import keys for Spotify
# TODO: Import keys for Mullvad
yay -S --needed --removemake --nocleanmenu --nodiffmenu --noeditmenu --noconfirm \
                dive \
                git-delta-bin \
                google-cloud-sdk \
                ttf-icomoon-feather \
                insomnia-bin \
                lazydocker \
                lazygit \
                mullvad-vpn-bin \
                nerd-fonts-iosevka \
                nodejs \
                npm \
                nvm \
                polybar \
                spicetify-cli \
                spotify \
                tmuxinator \
                zsh-fast-syntax-highlighting


# ====================================
# Polybar font
# ====================================

# Make pacman and yay colorful and adds eye candy on the progress bar because why not.
grep -q "^Color" /etc/pacman.conf || sudo sed -i "s/^#Color$/Color/" /etc/pacman.conf
grep -q "ILoveCandy" /etc/pacman.conf || sudo sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf

# Make a symlink for programs that look for "firefox"
sudo ln -s /usr/bin/firefox-developer-edition /usr/bin/firefox

# configure ssh agent
systemctl --user enable --now ssh-agent.service

# configure touchpad settings
if [[ $(hostname -s) = asgard ]]; then
sudo tee /etc/X11/xorg.conf.d/30-touchpad.conf > /dev/null << EOF
Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "NaturalScrolling" "true"
        Option "Tapping" "on"
        Option "TappingButtonMap" "lrm"
EndSection
EOF
fi

# Disable sudo password prompt timeout
sudo grep -xq "Defaults passwd_timeout=0" /etc/sudoers || sudo sh -c 'echo "Defaults passwd_timeout=0" >> /etc/sudoers'

# must be run once to configure nvm
source /usr/share/nvm/init-nvm.sh

# create folder for ZSH history
mkdir -p "${XDG_CACHE_HOME:-$HOME/.cache}/zsh"

echo "=============="
echo "==== DONE ===="
echo "=============="
echo "$ chsh -s /bin/zsh"
echo "$ startx"
echo "$ feh --bg-fill ~/.config/wallpaper.png"
