#!/bin/sh
set -e

# Make pacman and yay colorful and adds eye candy on the progress bar because why not.
sudo sed -i "s/^#Color$/Color/" /etc/pacman.conf
grep -q "^ILoveCandy" /etc/pacman.conf || sudo sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf
grep -q "^ParallelDownloads" /etc/pacman.conf || sudo sed -i "/#VerbosePkgLists/a ParallelDownloads = 5" /etc/pacman.conf

# set golang vars before installing anything for go
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export GOBIN="${GOPATH}/bin"

sudo pacman -Syuu --noconfirm

# ====================================
# Install packages
# ====================================

# dig is part of bind-tools
# hostname is part of inetutils
sudo pacman -S --noconfirm --needed \
	alacritty \
	base-devel \
	bc \
	bind-tools \
	chromium \
	cargo-nextest \
	ctags \
	curl \
	difftastic \
	dunst \
	fd \
	feh \
	firefox-developer-edition \
	flameshot \
	fzf \
	gdu \
	git-delta \
	gnome-themes-extra \
	go \
	htop \
	i3-wm \
	i3lock \
	inetutils \
	jq \
	k9s \
	kubectl \
	kubectx \
	libnotify \
	libreoffice \
	lldb \
	maim \
	man-db \
	neovim \
	net-tools \
	nm-connection-editor \
	noto-fonts-cjk \
	ntfs-3g \
	openssh \
	perl-image-exiftool \
	picom \
	pulseaudio-alsa \
	pulsemixer \
	pyenv \
	python-pip \
	python-poetry \
	python-pynvim \
	python-pywal \
	python3 \
	ripgrep \
	rofi \
	rust-analyzer \
	rustup \
	scrot \
	slock \
	sxiv \
	thunar \
	tmux \
	ttf-fira-code \
	ttf-iosevka-nerd \
	ttf-jetbrains-mono-nerd \
	udisks2 \
	unclutter \
	unzip \
	usbutils \
	vlc \
	wget \
	xclip \
	xdotool \
	xorg-mkfontscale \
	xorg-server \
	xorg-xinit \
	xorg-xrandr \
	xorg-xset \
	yarn \
	yq \
	zathura \
	zathura-pdf-mupdf \
	zip \
	zoxide \
	zsh \
	zsh-syntax-highlighting

if pacman -Qs yay >/dev/null; then
	echo "Yay is already installed, moving on..."
else
	pushd /tmp
	rm -rf yay
	git clone https://aur.archlinux.org/yay.git
	pushd yay
	makepkg -si --noconfirm
	popd
	rm -rf yay
	popd
fi

# Spotify usually requires manual work to install...
# https://aur.archlinux.org/packages/spotify
yay -S --needed --removemake --nocleanmenu --nodiffmenu --noeditmenu --noconfirm \
	bfg \
	bitwarden-cli \
	catppuccin-gtk-theme-mocha \
	dive \
	firefox-tridactyl-native-bin \
	gnome-themes-extra \
	gotop \
	gtk-engine-murrine \
	insomnia-bin \
	lazygit \
	lf \
	lua-format \
	mullvad-vpn-bin \
	noto-fonts-ar \
	nvm \
	polybar \
	spicetify-cli \
	tela-icon-theme-bin \
	tmuxinator \
	ttf-icomoon-feather \
	ttf-twemoji \
	zsh-fast-syntax-highlighting

# ====================================
# Polybar font
# ====================================

# configure ssh agent
systemctl --user enable --now ssh-agent.service

# configure touchpad settings
if [[ $(hostname -s) = asgard ]]; then
	sudo tee /etc/X11/xorg.conf.d/30-touchpad.conf >/dev/null <<EOF
Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "NaturalScrolling" "true"
        Option "Tapping" "on"
        Option "TappingButtonMap" "lrm"
EndSection
EOF
fi

# Disable sudo password prompt timeout
sudo grep -xq "Defaults passwd_timeout=0" /etc/sudoers || sudo sh -c 'echo "Defaults passwd_timeout=0" >> /etc/sudoers'

# must be run once to configure nvm
source /usr/share/nvm/init-nvm.sh

# create folder for ZSH history
mkdir -p "${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
# create folder for nvim
mkdir -p "${XDG_CACHE_HOME:-$HOME/.cache}/nvim/ctags"

touch "${XDG_CONFIG_HOME:-$HOME/.config}/pythonrc"

# Tmux plugin manager
TPM_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/tmux/plugins/tpm"
if [ ! -d "${TPM_PATH}" ]; then
	git clone https://github.com/tmux-plugins/tpm "${TPM_PATH}"
fi

rustup install stable
cargo install tmux-sessionizer

echo "=============="
echo "==== DONE ===="
echo "=============="
echo "$ chsh -s /bin/zsh"
echo "$ startx"
echo "$ feh --bg-fill ~/.config/wallpaper.png"
