local M = {}

M.theme = "catppuccin"

M.treesitter_ensure_installed = {
    "bash",
    "c",
    "c_sharp",
    "comment",
    "cpp",
    "cpp",
    "css",
    "diff",
    "dockerfile",
    "gitignore",
    "go",
    -- "hcl",
    "html",
    "java",
    "javascript",
    "jsonc",
    "latex",
    "lua",
    "markdown",
    "markdown_inline",
    "python",
    "query",
    "regex",
    -- "ruby",
    "rust",
    "scala",
    "scss",
    "toml",
    "typescript",
    "vim",
    "vimdoc",
    "yaml",
}

M.mason_tool_installer_ensure_installed = {
    "bash-language-server",
    "black",
    "codelldb",
    "debugpy",
    "dockerfile-language-server",
    "eslint_d",
    "json-lsp",
    "lua-language-server",
    "marksman",
    "nxls",
    "prettier",
    "pydocstyle",
    "pyright",
    "ruff",
    -- "shellcheck",
    "shfmt",
    "sql-formatter",
    "stylua",
    "terraform-ls",
    "texlab",
    "tflint",
    "typescript-language-server",
    "yaml-language-server",
    "yamllint",
}

return M
